/* js/voice-en-slow.js — נוצר אוטומטית ע"י tools/gen_voice.py (אל תערכו ידנית).
   מפת הקלטות קול טבעיות באנגלית: טקסט מנורמל → קובץ ב-assets/voice/en-slow */
window.VOICE_EN_SLOW = {
"apple": "apple.mp3",
"baby": "baby.mp3",
"ball": "ball.mp3",
"banana": "banana.mp3",
"bed": "bed.mp3",
"big": "big.mp3",
"bike": "bike.mp3",
"bird": "bird.mp3",
"black": "black.mp3",
"blue": "blue.mp3",
"boat": "boat.mp3",
"book": "book.mp3",
"bread": "bread.mp3",
"brother": "brother.mp3",
"bus": "bus.mp3",
"cake": "cake.mp3",
"car": "car.mp3",
"cat": "cat.mp3",
"chair": "chair.mp3",
"clock": "clock.mp3",
"coat": "coat.mp3",
"cold": "cold.mp3",
"cow": "cow.mp3",
"dad": "dad.mp3",
"dance": "dance.mp3",
"dog": "dog.mp3",
"door": "door.mp3",
"dress": "dress.mp3",
"duck": "duck.mp3",
"ears": "ears.mp3",
"eat": "eat.mp3",
"egg": "egg.mp3",
"eight": "eight.mp3",
"eyes": "eyes.mp3",
"fast": "fast.mp3",
"fish": "fish.mp3",
"five": "five.mp3",
"flower": "flower.mp3",
"foot": "foot.mp3",
"four": "four.mp3",
"friend": "friend.mp3",
"glasses": "glasses.mp3",
"grandma": "grandma.mp3",
"grandpa": "grandpa.mp3",
"green": "green.mp3",
"hair": "hair.mp3",
"hand": "hand.mp3",
"happy": "happy.mp3",
"hat": "hat.mp3",
"head": "head.mp3",
"horse": "horse.mp3",
"hot": "hot.mp3",
"house": "house.mp3",
"i can swim": "i-can-swim.mp3",
"i have two apples": "i-have-two-apples.mp3",
"i see a cat": "i-see-a-cat.mp3",
"jump": "jump.mp3",
"lamp": "lamp.mp3",
"lion": "lion.mp3",
"milk": "milk.mp3",
"mom": "mom.mp3",
"moon": "moon.mp3",
"mouth": "mouth.mp3",
"my mom is happy": "my-mom-is-happy.mp3",
"nose": "nose.mp3",
"one": "one.mp3",
"orange": "orange.mp3",
"pants": "pants.mp3",
"pink": "pink.mp3",
"pizza": "pizza.mp3",
"plane": "plane.mp3",
"rain": "rain.mp3",
"read": "read.mp3",
"red": "red.mp3",
"rocket": "rocket.mp3",
"run": "run.mp3",
"sad": "sad.mp3",
"sea": "sea.mp3",
"seven": "seven.mp3",
"shirt": "shirt.mp3",
"shoes": "shoes.mp3",
"sing": "sing.mp3",
"sister": "sister.mp3",
"six": "six.mp3",
"sleep": "sleep.mp3",
"slow": "slow.mp3",
"small": "small.mp3",
"snow": "snow.mp3",
"socks": "socks.mp3",
"star": "star.mp3",
"sun": "sun.mp3",
"swim": "swim.mp3",
"the ball is red": "the-ball-is-red.mp3",
"the bird can fly": "the-bird-can-fly.mp3",
"the dog is big": "the-dog-is-big.mp3",
"the sun is hot": "the-sun-is-hot.mp3",
"three": "three.mp3",
"train": "train.mp3",
"tree": "tree.mp3",
"truck": "truck.mp3",
"two": "two.mp3",
"water": "water.mp3",
"white": "white.mp3",
"yellow": "yellow.mp3"
};
