/* js/voice-en.js — נוצר אוטומטית ע"י tools/gen_voice.py (אל תערכו ידנית).
   מפת הקלטות קול טבעיות באנגלית: טקסט מנורמל → קובץ ב-assets/voice/en */
window.VOICE_EN = {
"a": "a.mp3",
"all": "all.mp3",
"am": "am.mp3",
"and": "and.mp3",
"angry": "angry.mp3",
"apple": "apple.mp3",
"at the zoo": "at-the-zoo.mp3",
"b": "b.mp3",
"baby": "baby.mp3",
"ball": "ball.mp3",
"banana": "banana.mp3",
"beach": "beach.mp3",
"bear": "bear.mp3",
"bed": "bed.mp3",
"best": "best.mp3",
"big": "big.mp3",
"bike": "bike.mp3",
"bird": "bird.mp3",
"black": "black.mp3",
"blue": "blue.mp3",
"boat": "boat.mp3",
"book": "book.mp3",
"bread": "bread.mp3",
"broccoli": "broccoli.mp3",
"brother": "brother.mp3",
"brown": "brown.mp3",
"bus": "bus.mp3",
"c": "c.mp3",
"cake": "cake.mp3",
"can": "can.mp3",
"car": "car.mp3",
"carrot": "carrot.mp3",
"cat": "cat.mp3",
"chair": "chair.mp3",
"cheese": "cheese.mp3",
"chicken": "chicken.mp3",
"chocolate": "chocolate.mp3",
"city": "city.mp3",
"clock": "clock.mp3",
"cloudy": "cloudy.mp3",
"coat": "coat.mp3",
"cold": "cold.mp3",
"colors": "colors.mp3",
"cookie": "cookie.mp3",
"corn": "corn.mp3",
"cow": "cow.mp3",
"crab": "crab.mp3",
"cucumber": "cucumber.mp3",
"cup": "cup.mp3",
"d": "d.mp3",
"dad": "dad.mp3",
"dance": "dance.mp3",
"do you like pizza": "do-you-like-pizza.mp3",
"dog": "dog.mp3",
"dolphin": "dolphin.mp3",
"door": "door.mp3",
"dress": "dress.mp3",
"duck": "duck.mp3",
"e": "e.mp3",
"ear": "ear.mp3",
"ears": "ears.mp3",
"eat": "eat.mp3",
"eats": "eats.mp3",
"egg": "egg.mp3",
"eight": "eight.mp3",
"elephant": "elephant.mp3",
"excellent": "excellent.mp3",
"eye": "eye.mp3",
"eyes": "eyes.mp3",
"f": "f.mp3",
"fast": "fast.mp3",
"fish": "fish.mp3",
"five": "five.mp3",
"flower": "flower.mp3",
"fly": "fly.mp3",
"foot": "foot.mp3",
"four": "four.mp3",
"fox": "fox.mp3",
"friend": "friend.mp3",
"frog": "frog.mp3",
"g": "g.mp3",
"giraffe": "giraffe.mp3",
"glasses": "glasses.mp3",
"go": "go.mp3",
"goes": "goes.mp3",
"good morning": "good-morning.mp3",
"good night": "good-night.mp3",
"goodbye": "goodbye.mp3",
"grandma": "grandma.mp3",
"grandpa": "grandpa.mp3",
"grapes": "grapes.mp3",
"grass": "grass.mp3",
"great answer": "great-answer.mp3",
"great job": "great-job.mp3",
"green": "green.mp3",
"h": "h.mp3",
"hair": "hair.mp3",
"hamster": "hamster.mp3",
"hand": "hand.mp3",
"happy": "happy.mp3",
"has": "has.mp3",
"hat": "hat.mp3",
"have": "have.mp3",
"head": "head.mp3",
"hello": "hello.mp3",
"hello you are a super hero let us learn some english words together": "hello-you-are-a-super-hero-let-u-0976ea.mp3",
"help": "help.mp3",
"hero": "hero.mp3",
"home": "home.mp3",
"hooray": "hooray.mp3",
"horse": "horse.mp3",
"hospital": "hospital.mp3",
"hot": "hot.mp3",
"house": "house.mp3",
"how are you": "how-are-you.mp3",
"how old are you": "how-old-are-you.mp3",
"i": "i.mp3",
"i am a super hero": "i-am-a-super-hero.mp3",
"i am blue": "i-am-blue.mp3",
"i am fine": "i-am-fine.mp3",
"i am happy": "i-am-happy.mp3",
"i am seven": "i-am-seven.mp3",
"i am six": "i-am-six.mp3",
"i can fly": "i-can-fly.mp3",
"i can swim": "i-can-swim.mp3",
"i fly over the city": "i-fly-over-the-city.mp3",
"i have a big red ball": "i-have-a-big-red-ball.mp3",
"i have a red ball": "i-have-a-red-ball.mp3",
"i have two apples": "i-have-two-apples.mp3",
"i help the cat hooray": "i-help-the-cat-hooray.mp3",
"i kick the ball": "i-kick-the-ball.mp3",
"i like all the colors": "i-like-all-the-colors.mp3",
"i like apples": "i-like-apples.mp3",
"i like blue": "i-like-blue.mp3",
"i like pink": "i-like-pink.mp3",
"i love my mom": "i-love-my-mom.mp3",
"i love the zoo": "i-love-the-zoo.mp3",
"i see a cat": "i-see-a-cat.mp3",
"i see a little cat": "i-see-a-little-cat.mp3",
"i'm fine": "i-m-fine.mp3",
"i'm fine thank you": "i-m-fine-thank-you.mp3",
"ice cream": "ice-cream.mp3",
"in": "in.mp3",
"is": "is.mp3",
"it is blue": "it-is-blue.mp3",
"it is raining": "it-is-raining.mp3",
"it is red": "it-is-red.mp3",
"j": "j.mp3",
"juice": "juice.mp3",
"jump": "jump.mp3",
"k": "k.mp3",
"key": "key.mp3",
"kick": "kick.mp3",
"l": "l.mp3",
"lamp": "lamp.mp3",
"like": "like.mp3",
"lion": "lion.mp3",
"little": "little.mp3",
"long": "long.mp3",
"love": "love.mp3",
"m": "m.mp3",
"me": "me.mp3",
"milk": "milk.mp3",
"mom": "mom.mp3",
"monkey": "monkey.mp3",
"moon": "moon.mp3",
"mouth": "mouth.mp3",
"my": "my.mp3",
"my colors": "my-colors.mp3",
"my dog is my best friend": "my-dog-is-my-best-friend.mp3",
"my dog runs to the ball": "my-dog-runs-to-the-ball.mp3",
"my mom is happy": "my-mom-is-happy.mp3",
"n": "n.mp3",
"nine": "nine.mp3",
"nose": "nose.mp3",
"o": "o.mp3",
"octopus": "octopus.mp3",
"one": "one.mp3",
"orange": "orange.mp3",
"over": "over.mp3",
"p": "p.mp3",
"pancakes": "pancakes.mp3",
"pants": "pants.mp3",
"park": "park.mp3",
"pasta": "pasta.mp3",
"pig": "pig.mp3",
"pink": "pink.mp3",
"pizza": "pizza.mp3",
"plane": "plane.mp3",
"potato": "potato.mp3",
"purple": "purple.mp3",
"q": "q.mp3",
"queen": "queen.mp3",
"r": "r.mp3",
"rabbit": "rabbit.mp3",
"rain": "rain.mp3",
"rainbow": "rainbow.mp3",
"rainy": "rainy.mp3",
"read": "read.mp3",
"red": "red.mp3",
"rocket": "rocket.mp3",
"run": "run.mp3",
"runs": "runs.mp3",
"s": "s.mp3",
"sad": "sad.mp3",
"scared": "scared.mp3",
"school": "school.mp3",
"sea": "sea.mp3",
"see": "see.mp3",
"seven": "seven.mp3",
"shark": "shark.mp3",
"sheep": "sheep.mp3",
"shirt": "shirt.mp3",
"shoe": "shoe.mp3",
"shoes": "shoes.mp3",
"sing": "sing.mp3",
"sister": "sister.mp3",
"six": "six.mp3",
"sky": "sky.mp3",
"sleep": "sleep.mp3",
"slow": "slow.mp3",
"small": "small.mp3",
"smile": "smile.mp3",
"snow": "snow.mp3",
"snowy": "snowy.mp3",
"socks": "socks.mp3",
"star": "star.mp3",
"strawberry": "strawberry.mp3",
"sun": "sun.mp3",
"sunny": "sunny.mp3",
"super": "super.mp3",
"supermarket": "supermarket.mp3",
"surprised": "surprised.mp3",
"swim": "swim.mp3",
"t": "t.mp3",
"ten": "ten.mp3",
"thank you": "thank-you.mp3",
"the": "the.mp3",
"the apple is red": "the-apple-is-red.mp3",
"the ball goes up up up": "the-ball-goes-up-up-up.mp3",
"the ball is red": "the-ball-is-red.mp3",
"the big red ball": "the-big-red-ball.mp3",
"the bird can fly": "the-bird-can-fly.mp3",
"the dog can run": "the-dog-can-run.mp3",
"the dog is big": "the-dog-is-big.mp3",
"the elephant has a long nose": "the-elephant-has-a-long-nose.mp3",
"the fish can swim": "the-fish-can-swim.mp3",
"the fish swim in the water": "the-fish-swim-in-the-water.mp3",
"the grass is green": "the-grass-is-green.mp3",
"the lion is big and yellow": "the-lion-is-big-and-yellow.mp3",
"the monkey eats a banana": "the-monkey-eats-a-banana.mp3",
"the sky is blue": "the-sky-is-blue.mp3",
"the sun is hot": "the-sun-is-hot.mp3",
"the sun is yellow": "the-sun-is-yellow.mp3",
"this": "this.mp3",
"this is me": "this-is-me.mp3",
"three": "three.mp3",
"tiger": "tiger.mp3",
"tired": "tired.mp3",
"to": "to.mp3",
"today": "today.mp3",
"today we go to the zoo": "today-we-go-to-the-zoo.mp3",
"tomato": "tomato.mp3",
"tooth": "tooth.mp3",
"train": "train.mp3",
"tree": "tree.mp3",
"truck": "truck.mp3",
"turtle": "turtle.mp3",
"two": "two.mp3",
"u": "u.mp3",
"umbrella": "umbrella.mp3",
"up": "up.mp3",
"v": "v.mp3",
"violin": "violin.mp3",
"w": "w.mp3",
"water": "water.mp3",
"watermelon": "watermelon.mp3",
"we": "we.mp3",
"well done": "well-done.mp3",
"whale": "whale.mp3",
"what color do you like": "what-color-do-you-like.mp3",
"what color is the sky": "what-color-is-the-sky.mp3",
"what starts with a": "what-starts-with-a.mp3",
"what starts with b": "what-starts-with-b.mp3",
"what starts with c": "what-starts-with-c.mp3",
"what starts with d": "what-starts-with-d.mp3",
"what starts with e": "what-starts-with-e.mp3",
"what starts with f": "what-starts-with-f.mp3",
"what starts with g": "what-starts-with-g.mp3",
"what starts with h": "what-starts-with-h.mp3",
"what starts with i": "what-starts-with-i.mp3",
"what starts with j": "what-starts-with-j.mp3",
"what starts with k": "what-starts-with-k.mp3",
"what starts with l": "what-starts-with-l.mp3",
"what starts with m": "what-starts-with-m.mp3",
"what starts with n": "what-starts-with-n.mp3",
"what starts with o": "what-starts-with-o.mp3",
"what starts with p": "what-starts-with-p.mp3",
"what starts with q": "what-starts-with-q.mp3",
"what starts with r": "what-starts-with-r.mp3",
"what starts with s": "what-starts-with-s.mp3",
"what starts with t": "what-starts-with-t.mp3",
"what starts with u": "what-starts-with-u.mp3",
"what starts with v": "what-starts-with-v.mp3",
"what starts with w": "what-starts-with-w.mp3",
"what starts with y": "what-starts-with-y.mp3",
"what starts with z": "what-starts-with-z.mp3",
"white": "white.mp3",
"windy": "windy.mp3",
"write": "write.mp3",
"x": "x.mp3",
"y": "y.mp3",
"yellow": "yellow.mp3",
"yes": "yes.mp3",
"yes i do": "yes-i-do.mp3",
"yes please": "yes-please.mp3",
"yo yo": "yo-yo.mp3",
"you are a super hero": "you-are-a-super-hero.mp3",
"z": "z.mp3",
"zebra": "zebra.mp3",
"zoo": "zoo.mp3"
};
