/* js/voice-en.js — נוצר אוטומטית ע"י tools/gen_voice.py (אל תערכו ידנית).
   מפת הקלטות קול טבעיות באנגלית: טקסט מנורמל → קובץ ב-assets/voice/en */
window.VOICE_EN = {
"a": "a.mp3",
"achoo": "achoo.mp3",
"airplane": "airplane.mp3",
"all": "all.mp3",
"am": "am.mp3",
"ambulance": "ambulance.mp3",
"and": "and.mp3",
"angry": "angry.mp3",
"apple": "apple.mp3",
"at the zoo": "at-the-zoo.mp3",
"b": "b.mp3",
"baa": "baa.mp3",
"baby": "baby.mp3",
"ball": "ball.mp3",
"banana": "banana.mp3",
"bandage": "bandage.mp3",
"barn": "barn.mp3",
"bath": "bath.mp3",
"beach": "beach.mp3",
"bear": "bear.mp3",
"bed": "bed.mp3",
"bee": "bee.mp3",
"beep beep": "beep-beep.mp3",
"best": "best.mp3",
"bicycle": "bicycle.mp3",
"big": "big.mp3",
"bike": "bike.mp3",
"bird": "bird.mp3",
"black": "black.mp3",
"blanket": "blanket.mp3",
"blue": "blue.mp3",
"blueberry": "blueberry.mp3",
"boat": "boat.mp3",
"book": "book.mp3",
"boost": "boost.mp3",
"bottom bun": "bottom-bun.mp3",
"brake": "brake.mp3",
"bread": "bread.mp3",
"broccoli": "broccoli.mp3",
"brother": "brother.mp3",
"brown": "brown.mp3",
"brush": "brush.mp3",
"bubbles": "bubbles.mp3",
"burger": "burger.mp3",
"bus": "bus.mp3",
"c": "c.mp3",
"cake": "cake.mp3",
"can": "can.mp3",
"car": "car.mp3",
"careful": "careful.mp3",
"carrot": "carrot.mp3",
"cat": "cat.mp3",
"chair": "chair.mp3",
"cheese": "cheese.mp3",
"cherry": "cherry.mp3",
"chicken": "chicken.mp3",
"chocolate": "chocolate.mp3",
"city": "city.mp3",
"clean": "clean.mp3",
"clock": "clock.mp3",
"cloudy": "cloudy.mp3",
"cluck": "cluck.mp3",
"coat": "coat.mp3",
"cold": "cold.mp3",
"colors": "colors.mp3",
"cone": "cone.mp3",
"cones": "cones.mp3",
"cook": "cook.mp3",
"cookie": "cookie.mp3",
"corn": "corn.mp3",
"count": "count.mp3",
"cow": "cow.mp3",
"crab": "crab.mp3",
"crosswalk": "crosswalk.mp3",
"cucumber": "cucumber.mp3",
"cup": "cup.mp3",
"d": "d.mp3",
"dad": "dad.mp3",
"dance": "dance.mp3",
"dirty": "dirty.mp3",
"do you like pizza": "do-you-like-pizza.mp3",
"doctor": "doctor.mp3",
"dog": "dog.mp3",
"dolphin": "dolphin.mp3",
"donut": "donut.mp3",
"door": "door.mp3",
"dress": "dress.mp3",
"drive to the black gate": "drive-to-the-black-gate.mp3",
"drive to the blue gate": "drive-to-the-blue-gate.mp3",
"drive to the green gate": "drive-to-the-green-gate.mp3",
"drive to the orange gate": "drive-to-the-orange-gate.mp3",
"drive to the purple gate": "drive-to-the-purple-gate.mp3",
"drive to the red gate": "drive-to-the-red-gate.mp3",
"drive to the white gate": "drive-to-the-white-gate.mp3",
"drive to the yellow gate": "drive-to-the-yellow-gate.mp3",
"drop": "drop.mp3",
"duck": "duck.mp3",
"e": "e.mp3",
"ear": "ear.mp3",
"ears": "ears.mp3",
"eat": "eat.mp3",
"eats": "eats.mp3",
"egg": "egg.mp3",
"eggs": "eggs.mp3",
"eight": "eight.mp3",
"elephant": "elephant.mp3",
"excellent": "excellent.mp3",
"eye": "eye.mp3",
"eyes": "eyes.mp3",
"f": "f.mp3",
"farm": "farm.mp3",
"fast": "fast.mp3",
"fence": "fence.mp3",
"fetch": "fetch.mp3",
"fill up": "fill-up.mp3",
"fire truck": "fire-truck.mp3",
"fish": "fish.mp3",
"five": "five.mp3",
"five cones": "five-cones.mp3",
"flashlight": "flashlight.mp3",
"flock": "flock.mp3",
"flour": "flour.mp3",
"flower": "flower.mp3",
"fly": "fly.mp3",
"food": "food.mp3",
"foot": "foot.mp3",
"four": "four.mp3",
"four cones": "four-cones.mp3",
"fox": "fox.mp3",
"friend": "friend.mp3",
"frog": "frog.mp3",
"fruit salad": "fruit-salad.mp3",
"g": "g.mp3",
"gallop": "gallop.mp3",
"gas station": "gas-station.mp3",
"gate": "gate.mp3",
"gentle": "gentle.mp3",
"giraffe": "giraffe.mp3",
"glasses": "glasses.mp3",
"go": "go.mp3",
"goes": "goes.mp3",
"good dog": "good-dog.mp3",
"good horse": "good-horse.mp3",
"good job doctor": "good-job-doctor.mp3",
"good kitty": "good-kitty.mp3",
"good morning": "good-morning.mp3",
"good morning farm": "good-morning-farm.mp3",
"good night": "good-night.mp3",
"good night farm": "good-night-farm.mp3",
"goodbye": "goodbye.mp3",
"grandma": "grandma.mp3",
"grandpa": "grandpa.mp3",
"grapes": "grapes.mp3",
"grass": "grass.mp3",
"great answer": "great-answer.mp3",
"great driving": "great-driving.mp3",
"great job": "great-job.mp3",
"great riding": "great-riding.mp3",
"green": "green.mp3",
"green light go": "green-light-go.mp3",
"h": "h.mp3",
"hair": "hair.mp3",
"hamster": "hamster.mp3",
"hand": "hand.mp3",
"happy": "happy.mp3",
"has": "has.mp3",
"hat": "hat.mp3",
"have": "have.mp3",
"hay": "hay.mp3",
"head": "head.mp3",
"healthy": "healthy.mp3",
"heart": "heart.mp3",
"helicopter": "helicopter.mp3",
"hello": "hello.mp3",
"hello you are a super hero let us learn some english words together": "hello-you-are-a-super-hero-let-u-0976ea.mp3",
"helmet": "helmet.mp3",
"help": "help.mp3",
"here comes the airplane": "here-comes-the-airplane.mp3",
"hero": "hero.mp3",
"hiccup": "hiccup.mp3",
"home": "home.mp3",
"honey": "honey.mp3",
"hoof": "hoof.mp3",
"hooray": "hooray.mp3",
"hop": "hop.mp3",
"hop hop": "hop-hop.mp3",
"horse": "horse.mp3",
"hospital": "hospital.mp3",
"hot": "hot.mp3",
"hot soup": "hot-soup.mp3",
"house": "house.mp3",
"how are you": "how-are-you.mp3",
"how many": "how-many.mp3",
"how many cones": "how-many-cones.mp3",
"how old are you": "how-old-are-you.mp3",
"hungry": "hungry.mp3",
"i": "i.mp3",
"i am a super hero": "i-am-a-super-hero.mp3",
"i am blue": "i-am-blue.mp3",
"i am fine": "i-am-fine.mp3",
"i am happy": "i-am-happy.mp3",
"i am seven": "i-am-seven.mp3",
"i am six": "i-am-six.mp3",
"i can fly": "i-can-fly.mp3",
"i can swim": "i-can-swim.mp3",
"i fly over the city": "i-fly-over-the-city.mp3",
"i have a big red ball": "i-have-a-big-red-ball.mp3",
"i have a red ball": "i-have-a-red-ball.mp3",
"i have two apples": "i-have-two-apples.mp3",
"i help the cat hooray": "i-help-the-cat-hooray.mp3",
"i kick the ball": "i-kick-the-ball.mp3",
"i like all the colors": "i-like-all-the-colors.mp3",
"i like apples": "i-like-apples.mp3",
"i like pink": "i-like-pink.mp3",
"i love my mom": "i-love-my-mom.mp3",
"i love the zoo": "i-love-the-zoo.mp3",
"i love you": "i-love-you.mp3",
"i see a cat": "i-see-a-cat.mp3",
"i see a little cat": "i-see-a-little-cat.mp3",
"i'm fine": "i-m-fine.mp3",
"i'm fine thank you": "i-m-fine-thank-you.mp3",
"ice": "ice.mp3",
"ice cream": "ice-cream.mp3",
"ice cream truck": "ice-cream-truck.mp3",
"in": "in.mp3",
"is": "is.mp3",
"it is blue": "it-is-blue.mp3",
"it is raining": "it-is-raining.mp3",
"it is red": "it-is-red.mp3",
"j": "j.mp3",
"juice": "juice.mp3",
"jump": "jump.mp3",
"k": "k.mp3",
"key": "key.mp3",
"kick": "kick.mp3",
"kiss": "kiss.mp3",
"l": "l.mp3",
"lamp": "lamp.mp3",
"let's cook": "let-s-cook.mp3",
"let's play": "let-s-play.mp3",
"lettuce": "lettuce.mp3",
"like": "like.mp3",
"lion": "lion.mp3",
"little": "little.mp3",
"long": "long.mp3",
"love": "love.mp3",
"m": "m.mp3",
"mane": "mane.mp3",
"me": "me.mp3",
"medicine": "medicine.mp3",
"meow": "meow.mp3",
"milk": "milk.mp3",
"milkshake": "milkshake.mp3",
"mix": "mix.mp3",
"mom": "mom.mp3",
"monkey": "monkey.mp3",
"monster truck": "monster-truck.mp3",
"moo": "moo.mp3",
"moon": "moon.mp3",
"motorcycle": "motorcycle.mp3",
"mouth": "mouth.mp3",
"mushroom": "mushroom.mp3",
"my": "my.mp3",
"my colors": "my-colors.mp3",
"my dog is my best friend": "my-dog-is-my-best-friend.mp3",
"my dog runs to the ball": "my-dog-runs-to-the-ball.mp3",
"my mom is happy": "my-mom-is-happy.mp3",
"n": "n.mp3",
"nest": "nest.mp3",
"nice turn": "nice-turn.mp3",
"nine": "nine.mp3",
"no thank you": "no-thank-you.mp3",
"nose": "nose.mp3",
"o": "o.mp3",
"octopus": "octopus.mp3",
"oil": "oil.mp3",
"olive": "olive.mp3",
"one": "one.mp3",
"one cone": "one-cone.mp3",
"onion": "onion.mp3",
"oops": "oops.mp3",
"open wide": "open-wide.mp3",
"orange": "orange.mp3",
"order up": "order-up.mp3",
"over": "over.mp3",
"p": "p.mp3",
"pancake": "pancake.mp3",
"pancakes": "pancakes.mp3",
"pants": "pants.mp3",
"park": "park.mp3",
"pasta": "pasta.mp3",
"patty": "patty.mp3",
"paw": "paw.mp3",
"pepper": "pepper.mp3",
"pig": "pig.mp3",
"pineapple": "pineapple.mp3",
"pink": "pink.mp3",
"pizza": "pizza.mp3",
"plane": "plane.mp3",
"play": "play.mp3",
"police car": "police-car.mp3",
"pond": "pond.mp3",
"potato": "potato.mp3",
"purple": "purple.mp3",
"purr": "purr.mp3",
"q": "q.mp3",
"quack": "quack.mp3",
"queen": "queen.mp3",
"quiet": "quiet.mp3",
"r": "r.mp3",
"rabbit": "rabbit.mp3",
"race car": "race-car.mp3",
"rain": "rain.mp3",
"rainbow": "rainbow.mp3",
"rainy": "rainy.mp3",
"read": "read.mp3",
"red": "red.mp3",
"red light stop": "red-light-stop.mp3",
"ride to the blue gate": "ride-to-the-blue-gate.mp3",
"ride to the gate": "ride-to-the-gate.mp3",
"ride to the green gate": "ride-to-the-green-gate.mp3",
"ride to the orange gate": "ride-to-the-orange-gate.mp3",
"ride to the pink gate": "ride-to-the-pink-gate.mp3",
"ride to the purple gate": "ride-to-the-purple-gate.mp3",
"ride to the red gate": "ride-to-the-red-gate.mp3",
"ride to the yellow gate": "ride-to-the-yellow-gate.mp3",
"ripe": "ripe.mp3",
"road": "road.mp3",
"rocket": "rocket.mp3",
"roll over": "roll-over.mp3",
"ruler": "ruler.mp3",
"run": "run.mp3",
"runs": "runs.mp3",
"s": "s.mp3",
"sad": "sad.mp3",
"saddle": "saddle.mp3",
"safe": "safe.mp3",
"sandwich": "sandwich.mp3",
"save": "save.mp3",
"say ah": "say-ah.mp3",
"scared": "scared.mp3",
"school": "school.mp3",
"sea": "sea.mp3",
"see": "see.mp3",
"seed": "seed.mp3",
"seeds": "seeds.mp3",
"sell": "sell.mp3",
"seven": "seven.mp3",
"shade": "shade.mp3",
"shake": "shake.mp3",
"shark": "shark.mp3",
"sheep": "sheep.mp3",
"shirt": "shirt.mp3",
"shoe": "shoe.mp3",
"shoes": "shoes.mp3",
"sing": "sing.mp3",
"sister": "sister.mp3",
"sit": "sit.mp3",
"six": "six.mp3",
"six cones": "six-cones.mp3",
"sky": "sky.mp3",
"sleep": "sleep.mp3",
"slow": "slow.mp3",
"small": "small.mp3",
"smile": "smile.mp3",
"smoothie": "smoothie.mp3",
"snow": "snow.mp3",
"snowy": "snowy.mp3",
"sock": "sock.mp3",
"socks": "socks.mp3",
"soup": "soup.mp3",
"spin": "spin.mp3",
"spoon": "spoon.mp3",
"sports car": "sports-car.mp3",
"sprinkles": "sprinkles.mp3",
"stand up": "stand-up.mp3",
"star": "star.mp3",
"stethoscope": "stethoscope.mp3",
"stop": "stop.mp3",
"strawberry": "strawberry.mp3",
"sugar": "sugar.mp3",
"sun": "sun.mp3",
"sunny": "sunny.mp3",
"super": "super.mp3",
"supermarket": "supermarket.mp3",
"surprise": "surprise.mp3",
"surprised": "surprised.mp3",
"swim": "swim.mp3",
"t": "t.mp3",
"taxi": "taxi.mp3",
"tea": "tea.mp3",
"ten": "ten.mp3",
"thank you": "thank-you.mp3",
"the": "the.mp3",
"the apple is red": "the-apple-is-red.mp3",
"the ball goes up up up": "the-ball-goes-up-up-up.mp3",
"the ball is red": "the-ball-is-red.mp3",
"the big red ball": "the-big-red-ball.mp3",
"the bird can fly": "the-bird-can-fly.mp3",
"the dog can run": "the-dog-can-run.mp3",
"the dog is big": "the-dog-is-big.mp3",
"the elephant has a long nose": "the-elephant-has-a-long-nose.mp3",
"the fish can swim": "the-fish-can-swim.mp3",
"the fish swim in the water": "the-fish-swim-in-the-water.mp3",
"the grass is green": "the-grass-is-green.mp3",
"the lion is big and yellow": "the-lion-is-big-and-yellow.mp3",
"the monkey eats a banana": "the-monkey-eats-a-banana.mp3",
"the sky is blue": "the-sky-is-blue.mp3",
"the sun is hot": "the-sun-is-hot.mp3",
"the sun is yellow": "the-sun-is-yellow.mp3",
"thermometer": "thermometer.mp3",
"this": "this.mp3",
"this is me": "this-is-me.mp3",
"three": "three.mp3",
"three cones": "three-cones.mp3",
"tiger": "tiger.mp3",
"time for a bath": "time-for-a-bath.mp3",
"tired": "tired.mp3",
"tissue": "tissue.mp3",
"to": "to.mp3",
"today": "today.mp3",
"today we go to the zoo": "today-we-go-to-the-zoo.mp3",
"tomato": "tomato.mp3",
"tooth": "tooth.mp3",
"toothbrush": "toothbrush.mp3",
"top bun": "top-bun.mp3",
"touch the black": "touch-the-black.mp3",
"touch the blue": "touch-the-blue.mp3",
"touch the green": "touch-the-green.mp3",
"touch the orange": "touch-the-orange.mp3",
"touch the pink": "touch-the-pink.mp3",
"touch the purple": "touch-the-purple.mp3",
"touch the red": "touch-the-red.mp3",
"touch the white": "touch-the-white.mp3",
"touch the yellow": "touch-the-yellow.mp3",
"towel": "towel.mp3",
"tractor": "tractor.mp3",
"traffic light": "traffic-light.mp3",
"train": "train.mp3",
"tree": "tree.mp3",
"truck": "truck.mp3",
"turbo": "turbo.mp3",
"turtle": "turtle.mp3",
"two": "two.mp3",
"two cones": "two-cones.mp3",
"u": "u.mp3",
"umbrella": "umbrella.mp3",
"up": "up.mp3",
"v": "v.mp3",
"vanilla": "vanilla.mp3",
"vet": "vet.mp3",
"violin": "violin.mp3",
"vroom": "vroom.mp3",
"w": "w.mp3",
"walk": "walk.mp3",
"wash": "wash.mp3",
"water": "water.mp3",
"watermelon": "watermelon.mp3",
"we": "we.mp3",
"well done": "well-done.mp3",
"whale": "whale.mp3",
"what color do you like": "what-color-do-you-like.mp3",
"what color is the sky": "what-color-is-the-sky.mp3",
"what starts with a": "what-starts-with-a.mp3",
"what starts with b": "what-starts-with-b.mp3",
"what starts with c": "what-starts-with-c.mp3",
"what starts with d": "what-starts-with-d.mp3",
"what starts with e": "what-starts-with-e.mp3",
"what starts with f": "what-starts-with-f.mp3",
"what starts with g": "what-starts-with-g.mp3",
"what starts with h": "what-starts-with-h.mp3",
"what starts with i": "what-starts-with-i.mp3",
"what starts with j": "what-starts-with-j.mp3",
"what starts with k": "what-starts-with-k.mp3",
"what starts with l": "what-starts-with-l.mp3",
"what starts with m": "what-starts-with-m.mp3",
"what starts with n": "what-starts-with-n.mp3",
"what starts with o": "what-starts-with-o.mp3",
"what starts with p": "what-starts-with-p.mp3",
"what starts with q": "what-starts-with-q.mp3",
"what starts with r": "what-starts-with-r.mp3",
"what starts with s": "what-starts-with-s.mp3",
"what starts with t": "what-starts-with-t.mp3",
"what starts with u": "what-starts-with-u.mp3",
"what starts with v": "what-starts-with-v.mp3",
"what starts with w": "what-starts-with-w.mp3",
"what starts with y": "what-starts-with-y.mp3",
"what starts with z": "what-starts-with-z.mp3",
"wheel": "wheel.mp3",
"where is the airplane": "where-is-the-airplane.mp3",
"where is the ambulance": "where-is-the-ambulance.mp3",
"where is the apple": "where-is-the-apple.mp3",
"where is the ball": "where-is-the-ball.mp3",
"where is the banana": "where-is-the-banana.mp3",
"where is the bicycle": "where-is-the-bicycle.mp3",
"where is the boat": "where-is-the-boat.mp3",
"where is the book": "where-is-the-book.mp3",
"where is the bus": "where-is-the-bus.mp3",
"where is the car": "where-is-the-car.mp3",
"where is the carrot": "where-is-the-carrot.mp3",
"where is the cat": "where-is-the-cat.mp3",
"where is the corn": "where-is-the-corn.mp3",
"where is the cow": "where-is-the-cow.mp3",
"where is the dog": "where-is-the-dog.mp3",
"where is the duck": "where-is-the-duck.mp3",
"where is the elephant": "where-is-the-elephant.mp3",
"where is the fire truck": "where-is-the-fire-truck.mp3",
"where is the fish": "where-is-the-fish.mp3",
"where is the flower": "where-is-the-flower.mp3",
"where is the frog": "where-is-the-frog.mp3",
"where is the grapes": "where-is-the-grapes.mp3",
"where is the helicopter": "where-is-the-helicopter.mp3",
"where is the horse": "where-is-the-horse.mp3",
"where is the house": "where-is-the-house.mp3",
"where is the lion": "where-is-the-lion.mp3",
"where is the monkey": "where-is-the-monkey.mp3",
"where is the moon": "where-is-the-moon.mp3",
"where is the motorcycle": "where-is-the-motorcycle.mp3",
"where is the orange": "where-is-the-orange.mp3",
"where is the police car": "where-is-the-police-car.mp3",
"where is the rabbit": "where-is-the-rabbit.mp3",
"where is the rocket": "where-is-the-rocket.mp3",
"where is the sheep": "where-is-the-sheep.mp3",
"where is the star": "where-is-the-star.mp3",
"where is the strawberry": "where-is-the-strawberry.mp3",
"where is the sun": "where-is-the-sun.mp3",
"where is the tractor": "where-is-the-tractor.mp3",
"where is the train": "where-is-the-train.mp3",
"where is the tree": "where-is-the-tree.mp3",
"where is the truck": "where-is-the-truck.mp3",
"where is the watermelon": "where-is-the-watermelon.mp3",
"whipped cream": "whipped-cream.mp3",
"white": "white.mp3",
"whoa": "whoa.mp3",
"windy": "windy.mp3",
"woof": "woof.mp3",
"wool": "wool.mp3",
"write": "write.mp3",
"x": "x.mp3",
"y": "y.mp3",
"yee haw": "yee-haw.mp3",
"yellow": "yellow.mp3",
"yellow light get ready": "yellow-light-get-ready.mp3",
"yes": "yes.mp3",
"yes i do": "yes-i-do.mp3",
"yes please": "yes-please.mp3",
"yo yo": "yo-yo.mp3",
"you are a super hero": "you-are-a-super-hero.mp3",
"yuck": "yuck.mp3",
"yummy": "yummy.mp3",
"z": "z.mp3",
"zebra": "zebra.mp3",
"zero": "zero.mp3",
"zoo": "zoo.mp3"
};
